FROM golang:1.19-buster AS build

WORKDIR /app

COPY service service
COPY client client
COPY cmd/client cmd/client
COPY go* .

RUN go mod download

RUN go build -o /app/client-exec ./cmd/client

FROM gcr.io/distroless/base-debian10

COPY --from=build /app/client-exec /app/client-exec

ENTRYPOINT ["/app/client-exec"]
