FROM golang:1.19-buster 

WORKDIR /app

COPY service service
COPY registry registry
COPY cmd/registry cmd/registry
COPY go* .

RUN go mod download

RUN go build -o /app/registry-exec ./cmd/registry

# FROM gcr.io/distroless/base-debian10

# COPY --from=build /app/registry-exec /app/registry-exec

ENTRYPOINT ["/app/registry-exec"]
