version: "3.9"

services:

  server_1:
    build:
      dockerfile: ./Dockerfile.server
    environment:
      ID: 1
      REGISTRY_URL: ${REGISTRY_URL}
      HOST_URL: host.docker.internal
      HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
      OTEL_SERVICE_NAME: raft-server-1
    volumes:
      - ./servers.yml:/servers.yml
  server_2:
    build:
      dockerfile: ./Dockerfile.server
    environment:
      ID: 2
      REGISTRY_URL: ${REGISTRY_URL}
      HOST_URL: host.docker.internal
      HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
      OTEL_SERVICE_NAME: raft-server-2
    volumes:
      - ./servers.yml:/servers.yml
  
  server_3:
    build:
      dockerfile: ./Dockerfile.server
    environment:
      ID: 3
      REGISTRY_URL: ${REGISTRY_URL}
      HOST_URL: host.docker.internal
      HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
      OTEL_SERVICE_NAME: raft-server-3
    volumes:
      - ./servers.yml:/servers.yml


  server_4:
    build:
      dockerfile: ./Dockerfile.server
    environment:
      ID: 4
      REGISTRY_URL: ${REGISTRY_URL}
      HOST_URL: host.docker.internal
      HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
      OTEL_SERVICE_NAME: raft-server-4
    volumes:
      - ./servers.yml:/servers.yml

  server_5:
    build:
      dockerfile: ./Dockerfile.server
    environment:
      ID: 5
      REGISTRY_URL: ${REGISTRY_URL}
      HOST_URL: host.docker.internal
      HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
      OTEL_SERVICE_NAME: raft-server-5
    volumes:
      - ./servers.yml:/servers.yml

