FROM golang:1.19-buster

WORKDIR /app

COPY service service
COPY client client
COPY cmd/client cmd/client
COPY go* .

RUN go mod download

RUN go build -o /app/client-exec ./cmd/client

ENTRYPOINT ["/app/client-exec"]
