FROM golang:1.19-buster 

WORKDIR /app

COPY service service
COPY server server
COPY cmd/server cmd/server
COPY go* .

RUN go mod download

RUN go build -o /app/server-exec ./cmd/server

# FROM gcr.io/distroless/base-debian10

# COPY --from=build /app/server-exec /app/server-exec

ENTRYPOINT ["/app/server-exec"]
