version: "3.9"

services:

  registry:
    build:
      context: .
      dockerfile: ./Dockerfile.registry
    environment:
      PORT: 50051
  server_1:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    environment:
      ID: 1
      REGISTRY_URL: registry:50051

  server_2:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    environment:
      ID: 2
      REGISTRY_URL: registry:50051
  
  server_3:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    environment:
      ID: 3
      REGISTRY_URL: registry:50051

  server_4:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    environment:
      ID: 4
      REGISTRY_URL: registry:50051

  server_5:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    environment:
      ID: 5
      REGISTRY_URL: registry:50051

