version: "3.9"
services:

  # Postgres
  postgres:
    image: postgres
    restart: always
    volumes:
      # Data storage
      - type: bind
        source: /tmp/buggy-app-data
        target: /var/lib/postgresql/data
      # Secrets (passwords etc.)
      - type: bind
        source: volumes/secrets
        target: /run/secrets
        read_only: true
      # Initialisation scripts (only run if data volume is empty)
      - type: bind
        source: volumes/init
        target: /docker-entrypoint-initdb.d
        read_only: true
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
      - POSTGRES_HOST=postgres
    ports:
      - "5432:5432"

  migrate:
    build: .
    depends_on:
      - postgres
    volumes:
      # Secrets (passwords etc.)
      - type: bind
        source: volumes/secrets
        target: /run/secrets
        read_only: true
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
    command: /out/migrate --path /migrations up
    profiles: ["migrate"]

  auth:
    build: .
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:2113:2112"
    depends_on:
      - postgres
    volumes:
      # Secrets (passwords etc.)
      - type: bind
        source: volumes/secrets
        target: /run/secrets
        read_only: true
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
    command: /out/auth

  api:
    build: .
    ports:
      - "127.0.0.1:8090:80"
      - "127.0.0.1:2112:2112"
    depends_on:
      - postgres
      - auth
    volumes:
      # Secrets (passwords etc.)
      - type: bind
        source: volumes/secrets
        target: /run/secrets
        read_only: true
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
    deploy:
      resources:
        limits:
          memory: 128M
    command: /out/api

  prometheus:
    image: prom/prometheus
    depends_on:
      - auth
      - api
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: volumes/prometheus
        target: /etc/prometheus
      - type: bind
        source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
  
  test:
    build: .
    depends_on:
      - postgres
    volumes:
      # Secrets (passwords etc.)
      - type: bind
        source: volumes/secrets
        target: /run/secrets
        read_only: true
    command: go test /app/... -cover
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
    profiles: ["test"]