global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'envoy'
    metrics_path: /metrics
    static_configs:
      - targets: ['10.10.0.5:9102', '10.10.0.6:9102']
        labels:
          group: 'envoy'