name: Docker Cloud test and deploy

on: [push]

defaults:
  run:
    working-directory: docker-cloud

jobs:
  test_app:
    name: Build and test go app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "docker-cloud/go.mod"
          cache-dependency-path: "docker-cloud/go.sum"
          cache: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
        with:
          tags: docker-cloud:latest

      - name: Test
        run: go test -v ./...

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: docker-cloud
          IMAGE_TAG: ${{ github.sha }}
        run: docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
