name: Multiple servers tests

on: [push]

defaults:
  run:
    working-directory: multiple-servers

jobs:
  test_app:
    name: Build and test go app
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: go_server_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "multiple-servers/go.mod"
          cache-dependency-path: "multiple-servers/go.sum"
          cache: true
      - name: Bild docker image
        run: docker build -t multi-aio:latest -f aio.Dockerfile .

      - name: Test
        run: DATABASE_URL=postgres://postgres:postgres@localhost:5432/go_server_db go test -v ./...