name: Test all applications

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Test go-ls
      run: cd cli-files/go-ls/cmd && go test -race -covermode=atomic -coverprofile=../coverage.out -v
    - name: Upload to codecov
      uses: codecov/codecov-action@v3

