name: Test all applications

on:
  push:
    branches:
      - main

jobs:
  test-and-upload-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Test go-ls
      run: cd cli-files/go-ls/cmd && go test -race -covermode=atomic -coverprofile=../coverage.out -v
    - name: Upload to codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: go-ls coverage
        files: ./cli-files/go-ls/coverage.out
    - name: Test go-cat
      run: cd cli-files/go-cat/cmd && go test -race -covermode=atomic -coverprofile=../coverage.out -v
    - name: Upload to codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: go-cat coverage
        files: ./cli-files/go-cat/coverage.out
    - name: Test http-auth
      run: cd http-auth && go test -race -covermode=atomic -coverprofile=coverage.out -v
    - name: Upload to codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: http-auth coverage
        files: ./http-auth/coverage.out
    

